### ISSUE TITLE
No such file or directory when running demo

### ISSUE THREAD

**Issue by jhomatas48** [hrlblab/CircleNet#11]
I am running into an error when I run this command in the circle_net_demo.ipynb file
```
!python run_detection_for_scn.py circledet --arch dla_34 --demo "/content/drive/My Drive/CircleNet/example_case/Case 03-1.scn" --load_model /content/drive/My\ Drive/CircleNet/trained_model/model_10.pth --filter_boarder --demo_dir "/content/drive/My Drive/CircleNet/demo_dir/test_demo"
```
Here is the traceback
```
Traceback (most recent call last):
  File "run_detection_for_scn.py", line 470, in <module>
    demo(opt)
  File "run_detection_for_scn.py", line 461, in demo
    run_one_scn(demo_scn, demo_dir, opt)
  File "run_detection_for_scn.py", line 241, in run_one_scn
    detector = Detector(opt)
  File "/content/drive/MyDrive/CircleNet/src/lib/detectors/circledet.py", line 23, in __init__
    super(CircledetDetector, self).__init__(opt)
  File "/content/drive/MyDrive/CircleNet/src/lib/detectors/base_detector.py", line 25, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "/content/drive/MyDrive/CircleNet/src/lib/models/model.py", line 34, in load_model
    checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/CircleNet/trained_model/model_10.pth'
```

**Comment by EthanHNguyen** [comment]
Hi! Thank you for your interest in our project. 

From the traceback, PyTorch cannot find the model. Make sure you have downloaded your model at the following directory: "/content/drive/My Drive/CircleNet/trained_model/model_10.pth"

You can download the model from: [https://github.com/hrlblab/CircleNet#circlenet---whole-slide-image-demo](https://github.com/hrlblab/CircleNet#circlenet---whole-slide-image-demo)
